---
name: Add to Project
run-name: 🚀 Adding ticket to PRs Project
on:
  pull_request:
    types:
      - opened
jobs:
  add-to-project:
    name: Add pull request to project
    runs-on: ubuntu-latest
    steps:
      - uses: actions/add-to-project@5afcf98fcd03f1c2f92c3c83f58ae24323cc57fd # v2.0.0
        with:
          project-url: https://github.com/orgs/greenfiling/projects/1/
          github-token: ${{ secrets.ADD_TO_PROJECT_PAT }}
